version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "Pyro.Api/"
    schedule:
      interval: "daily"
    assignees:
      - "sys27"
    reviewers:
      - "sys27"
    groups:
      ef-core:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      jwt:
        patterns:
          - "JWT*"
      aspnet:
        patterns:
          - "Microsoft.AspNetCore*"

  - package-ecosystem: "npm"
    directory: "Pyro.UI/"
    schedule:
      interval: "daily"
    assignees:
      - "sys27"
    reviewers:
      - "sys27"
    groups:
      angular:
        patterns:
          - "@angular/*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "sys27"
    reviewers:
      - "sys27"
