// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Pyro.Infrastructure.Issues.Migrations
{
    /// <inheritdoc />
    public partial class UpdateIssueStatusUniqueIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_IssueStatuses_Name",
                table: "IssueStatuses");

            migrationBuilder.DropIndex(
                name: "IX_IssueStatuses_RepositoryId",
                table: "IssueStatuses");

            migrationBuilder.CreateIndex(
                name: "IX_IssueStatuses_Name",
                table: "IssueStatuses",
                columns: new[] { "RepositoryId", "Name" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_IssueStatuses_Name",
                table: "IssueStatuses");

            migrationBuilder.CreateIndex(
                name: "IX_IssueStatuses_Name",
                table: "IssueStatuses",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_IssueStatuses_RepositoryId",
                table: "IssueStatuses",
                column: "RepositoryId");
        }
    }
}