// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Pyro.Infrastructure.Issues.Migrations
{
    /// <inheritdoc />
    public partial class AddStatuses : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "StatusId",
                table: "Issues",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateTable(
                name: "IssueStatuses",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    Color = table.Column<int>(type: "INTEGER", nullable: false),
                    RepositoryId = table.Column<Guid>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IssueStatuses", x => x.Id);
                    table.ForeignKey(
                        name: "FK_IssueStatuses_GitRepositories_RepositoryId",
                        column: x => x.RepositoryId,
                        principalTable: "GitRepositories",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "IssueStatusTransitions",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    FromId = table.Column<Guid>(type: "TEXT", nullable: false),
                    ToId = table.Column<Guid>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IssueStatusTranslations", x => x.Id);
                    table.ForeignKey(
                        name: "FK_IssueStatusTransitions_IssueStatuses_FromId",
                        column: x => x.FromId,
                        principalTable: "IssueStatuses",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_IssueStatusTransitions_IssueStatuses_ToId",
                        column: x => x.ToId,
                        principalTable: "IssueStatuses",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_Issues_StatusId",
                table: "Issues",
                column: "StatusId");

            migrationBuilder.CreateIndex(
                name: "IX_IssueStatuses_Name",
                table: "IssueStatuses",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_IssueStatuses_RepositoryId",
                table: "IssueStatuses",
                column: "RepositoryId");

            migrationBuilder.CreateIndex(
                name: "IX_IssueStatusTransitions_ToId",
                table: "IssueStatusTransitions",
                column: "ToId");

            migrationBuilder.CreateIndex(
                name: "IX_IssueStatusTranslations_FromId_ToId",
                table: "IssueStatusTransitions",
                columns: new[] { "FromId", "ToId" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Issue_Status",
                table: "Issues",
                column: "StatusId",
                principalTable: "IssueStatuses",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Issue_Status",
                table: "Issues");

            migrationBuilder.DropTable(
                name: "IssueStatusTransitions");

            migrationBuilder.DropTable(
                name: "IssueStatuses");

            migrationBuilder.DropIndex(
                name: "IX_Issues_StatusId",
                table: "Issues");

            migrationBuilder.DropColumn(
                name: "StatusId",
                table: "Issues");
        }
    }
}